---
label: Product Template
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
- type: text
  name: description
  label: description
- type: text
  name: price
  label: price
- type: text
  name: priceBefore
  label: priceBefore
- type: text
  name: shortDescription
  label: shortDescription
- type: text
  name: productID
  label: productID
- type: text
  name: type
  label: type
- name: categories
  type: list
  config:
    use_select: false
    min: 
    max: 
  label: Categories
- name: color
  type: list
  config:
    use_select: false
    min: 
    max: 
  label: Color
- name: size
  type: list
  config:
    use_select: false
    min: 
    max: 
  label: Size
- type: field_group_list
  name: images
  label: images
  fields:
  - type: file
    name: image
    label: image
- name: specifications
  type: field_group_list
  fields:
  - name: weight
    type: text
    config:
      required: false
    label: Weight
  - name: dimensions
    type: text
    config:
      required: false
    label: Dimensions
  - name: material
    type: text
    config:
      required: false
    label: Material
  - name: condition
    type: text
    config:
      required: false
    label: Condition
  - name: garmentcare
    type: text
    config:
      required: false
    label: Garment Care
  - name: closure
    type: text
    config:
      required: false
    label: Closure
  - name: noofpockets
    type: text
    config:
      required: false
    label: No. of Pockets
  - name: season
    type: text
    config:
      required: false
    label: Season
  config:
    min: 
    max: 
    labelField: 
  label: Specifications
pages:
- content/products/men-cotton-ribbed-blouson.md
- content/products/pink-floyd-bomber-jacket.md
